apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    application: pgwatch
    vendor: opensource.cybertec
  name: pgwatch-cm
data:
  launcher.sh: |
    #!/bin/sh

    CMD="/pgwatch/pgwatch"

    if [[ "$PG_IS_SINK" == "true" ]]; then
        CMD="$CMD --sink=postgresql://$PGWATCH_USER:$PGWATCH_USER_PASSWORD@$METRIC_DATABASE_ENDPOINT:$METRIC_DATABASE_PORT/$METRIC_DATABASE_DATABASE?sslmode=$METRIC_DATABASE_SSLMODE --retention=\"$PG_RETENTION_DAYS\""
    fi

    if [[ "$PROM_IS_SINK" == "true" ]]; then
        CMD="$CMD --sink=prometheus://0.0.0.0:9188/pgwatch"
    fi

    eval exec $CMD

