{{- if eq .Values.pgwatch.prometheus.new_prometheus.create_prometheus "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator-monitoring
    vendor: opensource.cybertec
  name: pgwatch-prometheus-cm
data:
  prometheus.yml: |
    ---
    global:
      scrape_interval: 1m
      scrape_timeout: 15s
      evaluation_interval: 5s

    scrape_configs:
    - job_name: 'pgwatch'
      static_configs:
        - targets: ['pgwatch-svc.{{ .Release.Namespace }}.svc.cluster.local:9188']

    rule_files:
      - /etc/prometheus/alert-rules.d/*.yml
{{ end }}
